docs : 구현할 기능 목록 작성
kth496/java-baseball-implement pull request #1
Opened 2022-03-03 15:47 UTC by ShinjaeKwon

2022-03-04 02:43 UTC, kth496 commented
@ShinjaeKwon PR은 하나로만 작성해주시면 됩니다! 지금 이 PR은 그대로 두시면 앞으로 커밋을 추가할때 자동으로 이곳으로 넘어올거에요. 그러면 완성된 이후에 PR에 설명도 같이 달아저 최종 제출해주시면 됩니다.

2022-03-04 06:11 UTC, ShinjaeKwon commented
넵 알겠습니다. 
깃 다루는게 처음이라 많이 헷갈리네요 
> 2022. 3. 4. 오전 11:44, Taehong Kim ***@***.***> 작성:
> 
> 
> @ShinjaeKwon <https://github.com/ShinjaeKwon> PR은 하나로만 작성해주시면 됩니다! 지금 이 PR은 그대로 두시면 앞으로 커밋을 추가할때 자동으로 이곳으로 넘어올거에요. 그러면 완성된 이후에 PR에 설명도 같이 달아저 최종 제출해주시면 됩니다.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/kth496/java-baseball-implement/pull/1#issuecomment-1058771473>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ATIT34CCQV6EKWUUNJV4AB3U6F2HLANCNFSM5P23PYWA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you were mentioned.
>

2022-03-05 17:05 UTC, ShinjaeKwon commented
구현 기능 목록을 작성하면서 로직을 크게 3개로 나눴습니다.
게임 전반적인 로직 기능, 사용자 답안 입력 기능, 답안 검사 기능으로 분리했습니다.
아래는 작성하면서 간단하게 그린 그림입니다.
[https://tartan-plot-7ea.notion.site/279b4834c9904abeadded8c50a6c6b9c](url)

1. feat : 게임 로직 기능 추가
간단하게 필요한 함수들의 껍데기와 랜덤값 받는 것까지 구현하였습니다.
처음 게임은 바로 시작되며, 그후 게임이 종료되면 사용자가 게임을 더 할지 종료할지 선택하게 하기위해 do-while 문을 사용하여 게임 로직 기능을 구현하였습니다.

2. feat : add user input method
처음에 문자열로 입력받아, 예외처리를 먼저 진행하였습니다. 
그 후 각 자릿수를 나눠, 중복되는 수에 대한 예외처리를 한 번 더 진행하였습니다.

3. feat : add check ans method
checkAnswer 함수를 기존에 if 문으로 만들었지만, 간단하게 연산자를 통해 비교할 수 있기때문에 다시 고쳤습니다. 
printBallAndStrike 함수는 각 숫자를 char[]로 변환해 비교합니다.
동일한 자릿수를 비교해 strike의 수를 얻어내고, 그 외에는 findBall 함수를 통해 한자리씩 비교하였습니다.
모든 자릿수를 비교한 후 strike와 ball의 갯수만큼 StringBuilder를 통해 힌트를 추가하였습니다.

4. fix : fix typo
모든 로직을 구현 한 후 Test를 돌려보는데 문제가 생겨서, 디버거를 통해 Exception 쪽에서 문제가 있다는 것을 발견하고, 이를 통해 IllegalArgumentException을 IllegalStateException 잘못 작성한 것을 찾아냈습니다. 
오탈자 수정으로 Test는 성공했습니다.

질문
1. 테스트케이스 및 디버거 상태에는 잘 돌아가는데 main 함수를 실행하고 숫자를 입력한 첫번째 힌트가 나온 후, 경고가 발생하는데, 어떻게 해결해야할지 잘 모르겠습니다. 일단 제 예상에는 nextstep에서 제공하는 API가 8버전 기반인데, 제가 11버전을 사용하고 있어 경고가 발생하는 거 같은데 구글링을 해봐도 해결을 못해서 질문드립니다.
아래는 경고 내용입니다.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by camp.nextstep.edu.missionutils.Console (file:/Users/shin/.gradle/caches/modules-2/files-2.1/com.github.woowacourse-projects/mission-utils/1.0.0/dad5230ec970560465a42a1cade24166e6a424f4/mission-utils-1.0.0.jar) to field java.util.Scanner.sourceClosed
WARNING: Please consider reporting this to the maintainers of camp.nextstep.edu.missionutils.Console
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

2. PR 작성을 이렇게 하는게 맞는지 잘 모르겠습니다.

2022-03-06 07:01 UTC, kth496 commented
@ShinjaeKwon 질문에 대해 답변드립니다!
1. JDK11의 리플렉션 관련 경고입니다! 8버전으로 바꾸시면 완전히 사라지네요. 경고이기 때문에 무시하고 그대로 진행하셔도 됩니다. 인텔리제이에는 편하게 다른 버전의 JDK설치하는 방법이 있는데 다음 시간에 알려드릴게요!
2. PR은 지금 하신것처럼 보내주시면 되는데 타이틀과 내용을 PR본문에 써주시는게 가장 좋습니다. 지금은 No description provided라고 되어있는 부분을 채워주시면 더 좋습니다.

2022-03-06 11:28 UTC, ShinjaeKwon commented
1. JDK 1.8 버전 찾아서 다운해보겠습니다.
2. 넵 수정하였습니다. 감사합니다.

2022-03-07 11:20 UTC, kth496 requested changes
전체적으로 클래스는 사용하지 않고 메인 메서드가 있는 `Application`에 모두 `static`으로 구현하셨는데요. 모두 한 클래스에 밀어넣지 마시고 역할과 책임에 맞게 분리해보는 연습을 해보세요.

2022-03-07 11:20 UTC, kth496 commented on src/main/java/baseball/Application.java
> +    }
한 메서드가 두 가지 일 이상을 하고 있네요. 한 메서드가 하나의 일만 하는 것이 가독성도 좋고 유지보수도 용이합니다. 여기서는 볼, 스트라이크의 갯수를 계산하는 로직과 출력하는 일 두 가지를 하고 있습니다.

2022-03-07 11:20 UTC, kth496 commented on src/main/java/baseball/Application.java
> +        return num;
똑같은 `IllegalArgumentException` 이라도 이유는 다르죠? 그렇기 때문에 메시지로 더 풍성한 정보를 제공해주면 어떤 이유인지 파악하기 더 쉽습니다. 여기서는 자릿수가 맞지않는경우, 0이 들어간 경우, 중복된 숫자가 있는 경우가 애매하게 분리되어 작성되어있어요. 하나로 합치지 않는다면 각각의 이유를 다르게 던져주는 것도 좋아보입니다.

2022-03-07 11:20 UTC, kth496 commented on README.md
> +임의의 3자리 숫자를 파라미터로 받고, 게임 로직을 진행한다.
기능 구현 목록은 말 그대로 기능 구현 목록만 작성하시면 됩니다. 설계와 구현, 메소드 이름등과 같은 사항은 너무 상세하게 적으실 필요 없어요. 왜냐하면 이러한 부분들은 언제든지 변경될 수 있는 코드의 영역이기 때문입니다. 이 게임에서 요구하는 기능 자체는 코드와 별개로 구성이 가능합니다. 실제로 사람과 사람이 게임을 한다고 생각하고 기능 중심으로 고민해보세요.

또한 현재 어떤 상황에서 예외가 발생하는지에 대한 정의가 작성되어있지 않습니다. 기능 명세는 예외적인 상황도 정리해야해요.

2022-03-07 11:20 UTC, kth496 commented on src/main/java/baseball/Application.java
> +        for (int i = 0; i < 3; i++) {
항상 의미있는 이름을 사용하는게 좋아요. 아무리 반복문이 간단해도 `i`와 같은 변수는 지양해야 합니다.

2022-03-07 13:06 UTC, ShinjaeKwon commented on src/main/java/baseball/Application.java
> +        int units = Randoms.pickNumberInRange(1, 9);
`Application`에 `static`으로 구현한 것들을 먼저 클래스로 분리하였습니다.
'AnswerChecking' 클래스는 답안 검사 및 결과를 출력하는 클래스
`RandomNumber` 클래스는 랜덤한 숫자 3자리를 만드는 클래스
`UserInputting` 클래스는 사용자 입력 및 예외처리 클래스
`GameLogic` 클래스는 전반적인 게임 로직을 담당하는 클래스
`Application` 클래스는 `GameLogic`만 호출하는 Main함수 역할을 하게 분리하였습니다.
`hundreds`는 변경되지 않으므로 상수 처리 하였고, `tens`와 `units`는 중복값으로 할당될경우 재할당 해야하기 때문에 변수로 그대로 나뒀습니다.

2022-03-07 13:07 UTC, ShinjaeKwon commented on src/main/java/baseball/Application.java
> +            if (!state) {
넵 `state`에서 `isAnswer` 이름으로 변경하였고, prefix 붙이는 방법을 더욱 활용해보겠습니다.

2022-03-07 13:10 UTC, ShinjaeKwon commented on src/main/java/baseball/Application.java
> +    }
`printBallStrike`메서드에서 strike와 ball 갯수를 세주는 기능과 갯수에 따른 힌트 출력의 기능이 같이 있어, `printHint`라는 새로운 메서드를 만들어 strike, ball의 값을 전달받아 그에 따라 결과를 출력해주도록 메서드를 만들었습니다.
또한 `printBallStrike`라는 이름이 맞지 않고, 이름을 통한 기능 예측을 할 수 없기 때문에 `countBallAndStrike`으로 메서드 명을 변경하였습니다.

2022-03-07 13:12 UTC, ShinjaeKwon commented on src/main/java/baseball/Application.java
> +        return num;
`IllegalArgumentException`을 3가지 경우에 따라 각각 다른 이유가 나오도록 변경하였습니다.

2022-03-07 13:13 UTC, ShinjaeKwon commented on README.md
> +임의의 3자리 숫자를 파라미터로 받고, 게임 로직을 진행한다.
메서드의 자세한 설명은 삭제하고, 어떤 기능으로 이루어져 있는지 알기쉽게 나눴습니다.
또한 어떤 상황에서 예외가 발생하는지 알려주고, 예시도 적어놨습니다.

2022-03-07 13:14 UTC, ShinjaeKwon commented on src/main/java/baseball/Application.java
> +        for (int i = 0; i < 3; i++) {
`i`의 역할이 자릿수를 의미하여 자릿수를 나타내는 `digit`로 이름을 변경하였습니다.

2022-03-07 17:42 UTC, kth496 requested changes
너무 잘 수정해주셨네요 ㅎㅎ 조금 더 디테일하게 짚어보겠습니다!

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/GameLogic.java
> +        return Integer.parseInt(Console.readLine());
이 메서드는 사실 게임의 메인 로직 이외에도 출력도 담당하고 있습니다. 출력만 따로 담당하는 클래스를 만들어보는건 어떨까요? 

예를 들어 우리의 게임이 잘 나가서 외국에도 진출한다고 가정해보겠습니다. 그러면 출력될 문자열을 다양한 외국어로 제공할 필요가 생깁니다. 출력 문자열만 번역해서 수정하려는데 `GameLogic`클래스를 수정해야 하는 상황이 발생하죠? 이는 논리적으로 이상하다는 것을 느끼실겁니다. 우리는 게임의 로직이 아니라 출력의 결과만을 수정하려는 의도인데, 그 목적을 달성하려면 게임 로직을 건드려야하는 상황이 되는 것이죠. 이러한 측면에서 고민해보시면 좋을 것 같습니다. 앞으로 모든 기능을 변경의 단위에서 바라보시면 분리하거나 합치는 일도 명확한 관점에서 판단하실 수 있을 거에요.

또한 여기 있는 문자열등도 모두 상수로 처리해주시는게 좋습니다. (값을 하드코딩하지 말라는 측면)

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/RandomNumber.java
> +        int units = Randoms.pickNumberInRange(1, 9);
상수로 분리하라는 뜻은 단순히 변수에 final 키워드를 붙이라는 의미가 아니라, 고정된 숫자를 하드코딩하지 말라는 의미입니다. 여기서는 `1` `9`등이 하드코딩 되어있습니다. 자바에서 상수는 `static final`로 선언합니다. 이 코드 외에 다른 클래스들에서도 상수가 잘못 선언된 부분이 많으니 챙겨서 수정해주세요!

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/RandomNumber.java
> +        int units = Randoms.pickNumberInRange(1, 9);
상수로 분리하라는 뜻은 단순히 변수에 final 키워드를 붙이라는 의미가 아니라, 고정된 숫자를 하드코딩하지 말라는 의미입니다. 여기서는 `1` `9`등이 하드코딩 되어있습니다. 자바에서 상수를 선언하는 방법에 대해 알아보고 적용해보세요.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/UserInputting.java
> +public class UserInputting {
`UserInputting`이라는 이름은 의미가 잘 와닿지 않는 것 같아요. "유저가 인풋하는중" 이렇게 들리네요. 제 생각에는 `UserInputHandler`정도가 좋아보입니다. 클래스명에는 일반적으로 흔히 쓰이는 표현들이 많이 있는데 `Handler`도 그중 하나입니다. 따로 언급하지는 않았지만 다른 클래스에도 적용해볼 수 있다면 시도해보셔도 좋을 듯 하네요.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/UserInputting.java
> +public class UserInputting {
`UserInputting`이라는 이름은 의미가 잘 와닿지 않는 것 같아요. "유저가 인풋하는중" 이렇게 들리네요. 제 생각에는 `UserInputHandler`정도가 좋아보입니다.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/UserInputting.java
> +        }
`throw new ...`가 계속 반복해서 나타나네요. 소프트웨어에서 만악의 근원이 바로 중복입니다. 중복을 잘 처리할 수 있는 방법은 무엇인지, 그 과정에서 문자열을 상수로 바꿔보는 것을 포함해 어떻게 분리하면 좋을지 고민해보세요.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/UserInputting.java
> +        }
`throw new ...`가 계속 반복해서 나타나네요. 소프트웨어에서 만악의 근원이 바로 중복입니다. 중복을 잘 처리할 수 있는 방법은 무엇인지, 그 과정에서 문자열을 상수로 바꿔보는 것을 포함해 어떻게 분리하면 좋을지 고민해보세요.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/AnswerChecking.java
> +public class AnswerChecking {
`AnswerChecking`클래스는 여러가지 일을 하고 있습니다.

1. 볼, 스트라이크 개수를 세어줌
2. 정답인지 확인해줌
3. 힌트를 출력함

클래스가 하나의 일을 하게 더 쪼개거나, 아니면 이 모든 것을 포괄할 수 있는 네이밍으로 변경하는것도 방법이 될 수 있습니다.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/AnswerChecking.java
> +public class AnswerChecking {
`AnswerChecking`클래스는 여러가지 일을 하고 있습니다.

1. 볼, 스트라이크 개수를 세어줌
2. 정답인지 확인해줌
3. 힌트를 출력함

클래스가 하나의 일을 하게 더 쪼개거나, 아니면 이 모든 것을 포괄할 수 있는 네이밍으로 변경하는것도 방법이 될 수 있습니다.

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/AnswerChecking.java
> +        System.out.println(sb);
`printHint`메서드는 힌트 결과를 만드는 일과 출력하는 일 두 가지를 하고 있네요. 분리하는게 좋아보입니다.(출력과 관련된 내용은 아래 다른 피드백 참고)

2022-03-07 17:42 UTC, kth496 commented on src/main/java/baseball/AnswerChecking.java
> +        System.out.println(sb);
`printHint`메서드는 힌트 결과를 만드는 일과 출력하는 일 두 가지를 하고 있네요. 분리하는게 좋아보입니다.(출력과 관련된 내용은 아래 다른 피드백 참고)

2022-03-09 05:22 UTC, ShinjaeKwon commented on src/main/java/baseball/GameLogic.java
> +        return Integer.parseInt(Console.readLine());
출력만 담당하는 `PrintHandler` 클래스를 새로 생성해서 출력하는 일만 담당하게 하였고, 문자열을 상수처리 하였습니다.

2022-03-09 05:27 UTC, ShinjaeKwon commented on src/main/java/baseball/RandomNumber.java
> +        int units = Randoms.pickNumberInRange(1, 9);
하드코딩된 값을 상수로 변경하였습니다.

2022-03-09 05:27 UTC, ShinjaeKwon commented on src/main/java/baseball/UserInputting.java
> +public class UserInputting {
Handler라는 이름을 다른 클래스에도 적용하였습니다.

2022-03-09 05:29 UTC, ShinjaeKwon commented on src/main/java/baseball/UserInputting.java
> +        }
`ExceptionHandler`라는 클래스를 새로 만들어 Exception에 관한 일을 처리하도록 하였고, 오류 메세지도 상수 처리하였습니다.
`throw new...` 의 중복 처리는 어떻게 해야할지 고민중입니다.

2022-03-09 05:41 UTC, ShinjaeKwon commented on src/main/java/baseball/AnswerChecking.java
> +public class AnswerChecking {
`AnswerChecking` 는 답과 플레이어 입력값이 같은지만 확인하는 역할로, `HintMaking`은 볼,스트라이크 값을 세주어 힌트를 만드는 역할로 나누었습니다.

2022-03-09 05:41 UTC, ShinjaeKwon commented on src/main/java/baseball/AnswerChecking.java
> +        System.out.println(sb);
print 하는 기능은 `PrintHandler`으로 옮겼습니다.

2022-03-11 15:59 UTC, closed without merging