숫자 야구 게임 구현
kth496/java-baseball-implement pull request #3
Opened 2022-03-08 13:10 UTC by eunbii0213

궁금한 점, 어려웠던 점 등을 씁니다.

2022-03-09 06:50 UTC, ShinHyoJung commented
intelliJ 설정이 한글로 되어있어서 저번에 함수 분리시키는 방법을 적용하지못했고,
볼과 스트라이크가 겹칠때는 스트라이크만 나오게 하고싶은데 잘 되지않았습니다
그리고 배열을 비교할때 겹쳐서 같은게 여러번 비교되는 경우를 제거해야겠다고 생각했습니다.

2022-03-10 04:19 UTC, kth496 commented
@eunbii0213 처음이라 어려우실텐데 고생많으셨어요! 남은 기능까지 구현되면 코드 리뷰를 작성할게요. 질문해주신 내용에 대한 답변은 다음과 같습니다.

> <질문사항>
> 지금은 기능들을 모두 구현하지 않았기 때문에 Player와 Computer같은 역할에 따른 클래스를 따로 만들진 않았지만 후에 그런 방향으로 수정하고싶습니다. 혹시 이렇게 코드를 짜면 채점에 문제가 생기게 될까요?

채점 자체는 요구사항에 작성된 입출력이 잘 수행되는지만 체크합니다. 그것만 만족된다면 원하시는 어떤 설계를 하더라도 무방해요. 말씀해주신 `Player` `Computer`등의 역할을 표현하는 클래스를 만드는 것은 좋은 방향이라고 생각해요 👍

2022-03-10 16:04 UTC, eunbii0213 commented
(03.10(목))
<질문사항>
IntelliJ에서 File -> ProjectStructure에서 temurin-1.8로 변경했음에도 불구하고 intelliJ내부에선 jdk가 17버전으로 뜹니다..! 
https://investechnews.com/2021/10/26/mac-zsh%EC%85%B8%EC%97%90%EC%84%9C-java-%ED%99%98%EA%B2%BD-%EB%B3%80%EC%88%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0-%EB%A7%A5-zsh-%EC%9E%90%EB%B0%94/

https://llighter.github.io/install-java-on-mac/

위의 두 사이트를 참고하여 따라해보았지만 macOs의 일반 터미널에서도 자바가 17버전에서 바뀌지를 않고있습니다 ㅠㅠ 어떻게 고쳐야할까요?

2022-03-10 16:19 UTC, eunbii0213 commented
(03.11(금))
곧 역할에 따른 Class 분리 작업 진행하여 다시 올리겠습니다!

2022-03-10 17:37 UTC, eunbii0213 commented
(03.11(금))
<질문사항>
1. static method안에서 일반method(static method가 아닌 method)를 호출하려고 하면 오류가 발생하는데 이유가 뭔가요?? 
2. 실수로 커밋해버린 경우(6b71ffb) 어떻게 커밋을 되돌릴 수 있을까요??

2022-03-10 17:50 UTC, eunbii0213 commented
(03.11(금))
기능 구현을 모두 마치고 테스트 또한 통과했습니다! 
소스코드 리뷰 및 질문사항 답변 부탁드립니다!

<질문사항>
1. static method안에서 일반method(static method가 아닌 method)를 호출하려고 하면 오류가 발생하는데 이유가 뭔가요?? 
2. 실수로 커밋해버린 경우(6b71ffb) 어떻게 커밋을 되돌릴 수 있을까요??

2022-03-11 13:47 UTC, kth496 commented
@eunbii0213 자바 환경 세팅이 꼬이면 어려운데 고생많으셨습니다! 코드 리뷰는 주말중으로 작성해둘게요! 질문해주신 내용에 대한 답변은 다음과 같습니다.

> 1. static method안에서 일반method(static method가 아닌 method)를 호출하려고 하면 오류가 발생하는데 이유가 뭔가요??

이 질문은 해석하기에 따라 다릅니다. 다만 어떤 의도로 질문하신지는 알겠네요. 자바에서는 기본적으로 static 메서드는 어떠한 인스턴스에 종속되지 않습니다. 반면 일반 method(non-static method)는 실제 객체, 인스턴스에 종속됩니다. 우리가 일반 메서드는 `instanceName.method()` 이러한 형태로 호출하죠? 일반 method끼리는 이미 객체가 존재하므로 상호 호출이 간단해집니다. 그냥 메서드명으로 호출만 하면 됩니다. 반면 static method 내부에서는 별도의 객체를 생성해야 합니다. 결론은, static method 내부에서 일반 method를 호출하려면 객체 참조가 없기 때문에 호출이 불가능하고요, 명시적으로 객체를 만들면 사실 호출은 됩니다. 아래 코드를 살펴보세요.

```java
public class Main {
	public static void main(String[] args) {
		Main main = new Main();
		main.printing();
	}

	public void printing() {
		System.out.println("TEST!!");
	}
}
```

<br>

> 2. 실수로 커밋해버린 경우 어떻게 커밋을 되돌릴 수 있을까요??

커밋을 되돌리는 것은 상당히 여러 방법으로 가능합니다. 가장 의도와 맞는 것은 intelliJ 의 git 메뉴를 이용해서 undo commit 하는 것입니다. 이건 다음에 한번 보여드릴게요! 이 외에 revert, rebase 등을 통해 커밋을 되돌리거나 정리하는 방법도 있습니다.

2022-03-11 16:20 UTC, kth496 requested changes
열심히 작성해주신 것이 느껴지네요. 고생하셨습니다! 아래에 코드 리뷰를 남겼으니 살펴보시고 반영해주세요~ 😃

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Application.java
> +                computer.ReOrEnd(player);
while문을 탈출하는 조건이 따로 존재하지 않고 `ReOrEnd` 메서드에서 `System.exit()`메서드를 호출해서 프로그램을 종료하고 있는데요. 이는 좋은 구조가 아닙니다. 지금처럼 간단한 조건이라면 어디서 프로그램이 종료될지 예측 가능하지만, 프로그램의 크기가 커지면 어디에서 `System.exit()`메서드가 호출되는지 하나씩 다 찾아봐야합니다. 예측 가능성의 측면에서 현재 구조보다는 while문을 탈출하게 하는게 더 좋습니다. 탈출하면 프로그램이 자연스레 끝나기도 하지요.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Application.java
> +import java.util.ArrayList;
불필요한 임포트문을 지워주세요.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Application.java
> +            if (computer.getStrike() == 3) {
값을 하드코딩하지 말고 상수로 분리해주세요!

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +    public void CalStrikeAndBall(Player player) {
변수나 메서드의 이름은 생략하지 않는 것이 좋습니다. 의도를 명확히 드러낸다면 긴 이름이라도 괜찮습니다!

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +        for (int i = 0; i < 3; i++) {
리스트 내부의 모든 요소를 순환할때는 인덱스로 직접 접근하기보다 `for-each`문법을 사용하는 것이 좋습니다. `for-each`에 대해 찾아보고 적용해보세요!

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +                setStrike(getStrike() + 1);
자기 자신의 멤버 변수에 접근하는데 굳이 `getter` `setter`를 사용할 필요는 없습니다.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +        System.out.println("3개의 숫자를 모두 맞히셨습니다! 게임 종료");
문자열도 모두 상수로 분리해주세요. 아울러 현재 구조에서는 `ReOrEnd` 메서드는 여러가지 일을 하고 있습니다. 출력을 하는 일과 게임 종료하는일, 유저의 인풋 검증부터 게임 재시작까지 너무나 많은 로직이 섞여 있습니다. 적절히 분리해주세요.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +            boolean checker = player.UserInputChecker(userInput, 1);
리턴된 `checker`변수가 쓰이지 않고 있습니다. 그렇다면 리턴이 존재할 필요가 있을까요? 만약 빼먹으신거라면 추가해주시고, 그렇지 않다면 void로 바꾸는 것이 좋아보여요.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +            System.out.println("낫싱");
if문이 상당히 복잡하게 구성되었네요. 더 간단하게 만들수는 없을까요? 게다가 `strike`나 `ball`을 출력하는 구문이 여러군데 중복되어 등작하고 있네요. 중복도 제거하셔야해요. 또한 64번 라인의 `strike == 0` 조건은 의미가 없네요. 앞서 0이 아님을 통과하고 온 상황이므로 여기서는 무조건 0입니다.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +    }
사용되지 않는 `getter` `setter`는 제거해주세요.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Player.java
> +    public ArrayList UserGuessNumber() throws IllegalArgumentException {
제네릭을 Raw 타입으로 사용하는 것은 좋지 않습니다. 타입을 붙여주세요.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Player.java
> +        }
`Computer` 클래스의 `ReOrEnd`메서드와 비슷하지 않나요? 비슷한 부분은 하나의 메서드로 분리해서 중복을 줄이는 것이 좋습니다. 

여기서 딜레마가 생깁니다. `Player`나 `Computer`나 모두 같은 체크 로직을 가집니다. 그렇다면 누구한테 이 로직을 줘야 할까요? 사실 한쪽으로 몰아넣기 힘든 상황입니다. 둘 다 이 게임에서의 참여자이기 때문이죠. 이 타이밍에 별도의 클래스가 필요하지는 않을지 고민할 필요가 있습니다.

예를 들어, 지금은 사용자가 `777`과 같은 입력을 넣어도 잘못된 입력으로 취급하지 않고 있어요. 분명 컴퓨터가 생성할때는 이러한 숫자가 만들어지지 않게 했지만 `Player`의 입력에서는 처리되지 않고 있지요. 바로 검증로직이 여러군데 흩어져있어서 발생한 실수 or 오류입니다.

2022-03-11 16:20 UTC, kth496 commented on src/main/java/baseball/Player.java
> +        }
아스키코드를 직접 다루기보다는 `Integer`클래스를 사용하는 것은 어떨까요? 이미 이곳에 숫자가 아닌 다른 입력에 대해 별도의 예외를 던져주는 기능이 있으니, 해당 예외를 잡아서 `IllegalArgumentException`로 변환해서 던지는게 더 좋습니다.

2022-03-12 15:17 UTC, eunbii0213 commented
(03.13(일))
1. 요구사항 반영하여 소스코드 수정
2. 사용자의 입력이 유효한지 검사하는 checker class생성
3. 대문자로 시작하는 method이름들을 소문자로 수정
하였습니다!! 소스코드 리뷰 부탁드립니다 🙂!!

+ 섬세한 피드백 감사드립니다!! 덕분에 쉽고 더 효율적으로 코드를 수정할 수 있었습니다!

2022-03-12 16:21 UTC, kth496 requested changes
다양한 부분에서 많이 수정해주셨네요! 열심히 하시는만큼 저도 피드백을 적극적으로 하게 됩니다 ㅎㅎ 코멘트가 조금 많을 수 있는데 하나씩 살펴보고 고민해보시면 좋을 것 같아요~

2022-03-12 16:21 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +    private static final String REORENDSTR = "게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요.";
문자열 상수 분리는 잘 하셨습니다! 작명은 약간 아쉽네요. 알아보기 쉽게 언더스코어를 적절히 사용해주면 좋을 것 같아요. 그리고 이것은 일종의 메시지이므로 접미사로 `STR`보다는 `MESSAGE`등이 더 적절해 보입니다.

2022-03-12 16:21 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +        }
스트라이크와 볼을 계산하는 로직에 갑자기 유저가 잘못 입력한 경우가 있는지 검사하고 있네요. 앞서 잘못된 유저의 인풋에 대한 검사를 했는데 거기서 다 되지 않은걸까요? 그렇다면 그 메서드로 옮기는게 좋아보입니다.

2022-03-12 16:21 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +                setBall(getBall() + 1);
`Computer` 클래스 내부에서 자기 자신의 `private`변수를 접근하는데 굳이 `getter` `setter`를 사용할 필요가 없습니다. 오히려 `setter`를 만들어두었기 때문에 외부에서 변경될 가능성만 커지게 됩니다.

2022-03-12 16:21 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +            }else if(userInputToInt ==2){
여기서 `Application.startGame()`이 다시 호출된다는 것에 주목해주세요. 지금 게임의 재시작이 재귀함수로 구현된 상황입니다. `startGame()`에서 마지막에 `reOrEnd()`를 호출하는데, 그 메서드 안에 들어오고 보니 조건에 따라서 `startGame()`을 다시 호출하는 구조에요. 게임이 많이 진행될수록 메서드 콜 스택이 계속 쌓입니다. 게임을 많이 하면 스택 오버플로우로 프로그램이 죽을 수 있습니다. 따라서 반드시 수정해야하는 구조입니다.

힌트: `do-while`문을 활용하시면 게임 재시작을 구현하기 편할 수 있습니다.

2022-03-12 16:21 UTC, kth496 commented on src/main/java/baseball/Computer.java
> +            }
저번 피드백 이후로 조건문은 조금 간단해졌는데 여전히 출력하는 로직이 산개되어 있습니다. 출력할 메시지를 조건문에서 구성하다가 마지막에 한번에 `System.out.println`으로 출력하는 방법이 가능할지 고민해보세요!

2022-03-14 03:05 UTC, eunbii0213 commented
(3.14(월))
<질문사항>
선생님! 게임종료 후 재시작 부분에서 timeout이 발생하면서 FAILED가 되는데 이유를 도저히 모르겠어요... 혹시 봐주실 수 있을까요? 😭

ApplicationTest > 게임종료_후_재시작() FAILED
    org.opentest4j.AssertionFailedError at ApplicationTest.java:15
        Caused by: org.junit.jupiter.api.AssertTimeout$ExecutionTimeoutException at ApplicationTest.java:34

오류는 이렇게 뜹니다..!

2022-03-14 12:36 UTC, kth496 commented
@eunbii0213 지금 은비님이 작성하신 코드에 버그가 있습니다. `Computer` 클래스에서 중복된 번호를 체크하는 `visited` 배열을 게임이 새로 시작하더라도 다시 초기화하지 않고 있습니다. 한번 직접 게임을 4판 실행해보세요. 3번째 게임까지는 잘 실행되지만 4번째부터 무한 루프에 빠질겁니다. 왜냐하면 3번 게임을 하면 1~9의 숫자를 3개씩 소모해서 마지막에 남는 숫자가 없기 때문입니다. 첫 게임에 `123`이 등장했다고 해서 다음 게임에 `234`처럼 일부 숫자가 겹치지 말아야 한다는 규칙은 없으므로 해당 부분을 수정해주시면 잘 동작할거에요.

2022-03-14 15:09 UTC, eunbii0213 commented
(03.15(화))
<변경사항>
1. 쓰지않는 매개변수 삭제
2. 피드백 반영하여 소스코드 수정
3. 게임 재시작 혹은 종료를 입력 받을 때도 하드코딩같아서 상수로 선언함 
4. 000같이 0을 포함하는 모든수들을 잘못된 입력이라고 판단(유저의 입력은 1부터 9까지로 제한 )
5. 길이검사>>문자검사에서 문자검사 >> 길이검사로 수정(유저가 a를 입력하면 길이보다는 문자 문제라고 판단하기)
6. timeout문제>> 선생님 피드백 + Application.java 안 while문에서의 if(!re)안의 re를 사용하고 원상복구 시켜주지 않아 timeout발생함을 찾음

<질문사항>
1. 사용하지 않는 getter와 setter를 지우라고 하셨는데 언급하신 getter와 setter 모두 다른 부분에서 사용을 합니다..! 그럼에도 지울 수 있게 코드를 수정해야할까요?
2. 예외처리기능에서 BUILD FAILED가 뜨는데 대체 이유를 모르겠습니다.. 선생님 도와주세요…!!!!

+선생님이 버그를 확실하게 언급해주신 덕분에 코드 수정에 큰 도움 받았습니다..! 감사합니다 🥺

2022-03-14 15:58 UTC, kth496 commented
@eunbii0213 

1번 질문에 대한 답변은 수요일에 직접 해드리겠습니다~ 2번 질문에 대한 답변을 드릴게요!

> 예외처리기능에서 BUILD FAILED가 뜨는데 대체 이유를 모르겠습니다.. 선생님 도와주세요…!!!!

예외처리기능 테스트에서 빌드가 실패하는 이유는 예외를 직접 던지지 않아서 그렇습니다. `e.printStackTrace();`로 스택 트레이스를 출력하지만 하는 것이 아니라, 그냥 `IllegalArgumentException`을 던지세요! 즉, `catch`를 하지 않는겁니다. 

[링크](https://github.com/kth496/java-baseball-implement#-%EA%B8%B0%EB%8A%A5-%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD)에 적힌 요구사항에는 다음과 같은 문장이 있습니다.

> 사용자가 잘못된 값을 입력할 경우 IllegalArgumentException을 발생시킨 후 애플리케이션은 종료되어야 한다.

발생시킨 후 종료라는것은 해당 예외를 던져서 비정상 종료하시면 된다는 뜻입니다!

2022-03-14 16:50 UTC, eunbii0213 commented
헉 네!!!!!! 말씀들으니 방금 번뜩하고 깨달았어요!!!! 열심히 수정해보겠습니다!!!! 감사합니다!!!

2022-03-14 17:26 UTC, eunbii0213 commented
🔥선생님..해냈습니다...!!🔥

2022-03-15 14:06 UTC, closed without merging