숫자 야구 게임 - 과제 제출
kth496/java-baseball-implement pull request #5
Opened 2022-03-15 18:58 UTC by Hepheir

2022-03-15 19:22 UTC, Hepheir commented
## 어려웠던 점 & 질문

`Randoms.pickUniqueNumbersInRange()` 메소드를 이용하고 싶었으나, `java.util`의 모든 기능을 사용하면 안된다는 제약에 `ArrayList`를 사용 할 수 없어 방법을 모색해보았습니다.

```java
ArrayList<Integer> result = Randoms.pickUniqueNumbersInRange(startInclusive, endInclusive, count);
```

먼저, 반환 값을 변수에 저장하지 않고 바로 사용하는방법을 떠올렸는데, `ArrayList.toArray()`의 방법을 사용하였습니다.

```java
int[] numbers = { -1, -1, -1 };
Randoms.pickUniqueNumbersInRange(1, 9, 3).toArray(numbers);
```

하지만 위 코드는 다음의 경고를 보여주며, 컴파일이 되지 않았습니다.

```text
The method toArray(T[]) in the type List<Integer> is not applicable for the arguments (int[])
```

타입 문제라고 생각하여 캐스팅을 해보려고 하였는데, 이 조차도 쉽지 않았습니다.

![image](https://user-images.githubusercontent.com/19310326/158454978-bfaeeb6e-3daf-41e7-9128-5f3a671e23e9.png)


여기서 궁금했던 것이, 왜 java는 `int`와 `Integer`가 구분되어있는지, 차이는 뭔지, 이런 경우에는 어떻게 처리하는게 좋은지 궁금했습니다.

2022-03-15 20:01 UTC, Hepheir commented
## 어려웠던 점

들여쓰기 depth를 3까지 허용하며 코드를 작성하는 것은 쉬운 반면, depth를 2로 유지하기 위해 고민을 더 해보아야 했던 것 같습니다.

특히 `countBalls()` 메소드를 구현할 때가 어려웠는데, 처음 아이디어는 2중 `for`문을 구성하여, 플레이어와 컴퓨터의 숫자를 비교하는 방식이었습니다. 이 경우에는 아래와 같이 depth가 3이 되어버렸습니다.

```java
@Override
public int countBalls() {
    int ballsCnt = 0;
    for (int i = 0; i < AMOUNT_OF_NUMBERS; i++) {
        for (int j = 0; j < AMOUNT_OF_NUMBERS; j++) {
            if (i == j) {
                continue;
            }

            if (getPlayerNumber(i) == getHostNumber(j)) {
                ballsCnt++;
            }
        }
    }
    return ballsCnt;
}
```

고민끝에 다음과 같이 메소드를 분리하였는데,

```java
@Override
public int countBalls() {
    int ballsCnt = 0;
    for (int i = 0; i < AMOUNT_OF_NUMBERS; i++) {
        int playerNumber = getPlayerNumber(i);
        int numberFoundAt = findNumberFromHostNumbers(playerNumber);
        if (numberFoundAt != -1 && numberFoundAt != i) {
            ballsCnt++;
        }
    }
    return ballsCnt;
}

private int findNumberFromHostNumbers(int number) {
    // Returns -1, if not found.
    for (int i = 0; i < AMOUNT_OF_NUMBERS; i++) {
        if (getHostNumber(i) == number) {
            return i;
        }
    }
    return -1;
}
```

이렇게 하는게 맞는걸까요?...

## 질문

생각해보면 Floyd-Warshall 알고리즘의 의사코드의 경우 depth가 4까지 도달하는데, 이런 알고리즘을 사용하게 되는 경우에도 메소드를 분리하게 되는지 문득 궁금해집니다.

```text
let dist be a |V| × |V| array of minimum distances initialized to ∞ (infinity)
for each edge (u,v)
   dist[u][v] ← w(u,v)  // 변 (u,v)의 가중치
for each vertex v
   dist[v][v] ← 0
for k from 1 to |V|
   for i from 1 to |V|
      for j from 1 to |V|
         if dist[i][j] > dist[i][k] + dist[k][j]
             dist[i][j] ← dist[i][k] + dist[k][j]
         end if
```

2022-03-15 20:49 UTC, Hepheir commented
스타일 가이드를 읽다보니, 되도록 한 파일에 하나의 탑레벨 클래스를 담는 것을 권장하네요. 위의 두 커밋에서 적용했습니다. ([9fc30e5](https://github.com/kth496/java-baseball-implement/pull/5/commits/9fc30e5c5071930503ced17d8609b9404b8615ec), [2f99f55](https://github.com/kth496/java-baseball-implement/pull/5/commits/2f99f5526e59aead9dbaac2094c17c841c219916))

> <img width="1005" alt="image" src="https://user-images.githubusercontent.com/19310326/158468621-e1e36b7d-e864-451a-a3a8-1aff901e07e1.png">

## 질문

그런데 궁금한 것이 있습니다. [AngularJS Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)에서 허용하는 커밋의 `<type>`중 위의 두 커밋의 타입 후보로 다음의 두 개를 생각했는데, 이 경우에는 어떤게 적절한 선택일까요,,

* style(Application): ...
* refactor(Application): ...

메시지 body도 어떻게 적어야할지 쉽사리 감각이 잡히지 않습니다.
커밋메시지 작성도 구현에 버금가게 어려운 것 같습니다.

2022-03-16 18:36 UTC, kth496 requested changes
현재 전체적으로 index를 직접 다루는 for문을 쓰고 계시는데 앞서 코멘트 드린 내용과 함께 반영하셔서 `List`와 `for-each`구문을 적극적으로 활용해보시면 좋을 것 같아요.

아울러 하나의 클래스에 모든 기능이 모여있는데, 역할과 책임이라는 관점에서 적절한 클래스로 분리해보시는 연습도 해보세요! `Application` 게임이 시작하는 용도로만 쓰시는 방향으로 해보시면 좋을 것 같습니다~

2022-03-16 18:36 UTC, kth496 commented on .gitattributes
> +*.java text eol=lf
불필요한 파일은 커밋하시면 안됩니다. 지금은 이 파일 포함해서 `gradle.yml` `.vscode`등이 포함되어 있으니 제외시켜주세요!

2022-03-16 18:36 UTC, kth496 commented on README.md
> +## 구현할 기능 목록 (과제)
구현할 기능 목록을 범주로 구분하여 작성해주신 부분은 아주 좋습니다!

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +    final int NUMBER_RANGE_END_INCLUSIVE = 9;
특별한 이유가 없다면 모든 접근 제한자는 `private`으로 통일하는 것이 좋습니다. 지금은 외부나 상속받은 클래스에서 사용할 경우가 없기도 합니다.

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Game.java
> +    public void end();
인터페이스는 기본적으로 접근 제한자가 `public`입니다. 따라서 위와 같이 쓰지 않아도 됩니다~

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +        assert checkIndex(index);
여기서 `assert`문으로 검증하는게 좋은 것은 아닙니다. 이유는 다음과 같습니다. (참고로 약간 다르게 작성하신 `checkValue`는 괜찮습니다. 저희 게임의 비즈니스 로직과 관련이 있기 때문이죠!)

1. `assert`가 없더라도 index를 넘어서면 `IndexOutOfBoundException`이 발생합니다. 이것만으로도 충분히 잘못된 사용에 대해 알려줄 수 있으며 표현력도 좋습니다.
2. `assert`문으로 검증했을 때 거짓이면 `AssertionError`가 발생합니다. `Exception`과 `Error`의 차이는 저번에 말씀드렸으니 생략하겠습니다. 아울러 위의 장점에서 명확한 예외 메시지가 나온 것에 비해 이유를 명확히 알기 어렵다는 단점도 있습니다.

python에서는 `assert` 패턴을 많이 사용하는 것으로 알고 있는데요. 자바에서는 비슷한 역할로 `requireNull`등의 별도 메서드를 사용하고는 합니다. 이것은 자바 기본 기능은 아니고 `apache`에서 제공하는 라이브러리에 들어있으니 관심 있다면 한번 살펴보세요~

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +        System.out.println();
현재 이 메서드는 출력에 대한 책임도 가지고 있고, 유저 입력을 처리하기도 합니다. 따라서 그 둘은 분리하는 것이 좋아요. `View`만을 처리하는 별도의 클래스를 만들어보는건 어떠신가요? 아울러 문자열이 하드코딩 되어 있는데 이 역시 상수로 분리하셔야 합니다.

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +    }
`move`라는 메서드명이 잘 와닿지 않네요. 조금 더 적절한 메서드명으로 바꿔보는건 어떠신가요?

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +    }
이 메서드는 굳이 제네릭으로 만들 이유가 없습니다. 제네릭으로 만드는 것은 어찌되었든 이해하기 한층 더 어렵게 하는 측면이 있으므로 꼭 필요할때만 사용하시는게 좋아요.

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +    private void parseRawPlayerNumbers(String[] rawPlayerNumbers) throws IllegalArgumentException {
`parseRawPlayerNumbers`라는 이름만 보면 파싱만 해서 리턴을 해줄 것 같은데 직접 플레이어의 입력으로 세팅도 해주고 있네요. 더 적절한 이름으로 변경하는건 어떠신가요?

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +        System.out.println();
이 메서드는 몇 가지 측면에서 개선이 가능해보여요~

1. 기준이 되는 숫자나 출력할 고정된 문자열이 상수로 분리될 수 있음
2. `System.out.print`를 매 라인에서 실행중
하나의 출력 결과물을 만들고 마지막에 출력하게 하는 구조로 개선이 가능해 보입니다. 이렇게 개선하면 출력이 어디서 이뤄질지 예측이 가능하며 흐름을 파악하기도 쉬우므로 한번 시도해보세요!

2022-03-16 18:36 UTC, kth496 commented on src/main/java/baseball/Application.java
> +        } while (app.promptStartNewGame());
여기서 `app.start()`로 실행했지만 `end`메서드는 따로 보이지 않는군요. 알고보니 `start`내부에 `end`도 같이 있는 구조네요. 우리가 생각하는 영문에서의 의미는 `start`라는 단어와 `end`라는 단어가 같은 레벨에서 받아들여집니다. 다시말해, 내가 보고 있는 어딘가에서 `start`가 되었다면, 같은 수준(여기서는 메서드 위치)에서 `end`또한 등장할거라 기대할 수 있다는 의미이죠. 지금의 구조에서는 `start`내부에 `end`가 있으니 약간 어색합니다.

구조 자체는 잘 잡혀 있으므로 이름만 바꿔보는건 어떨까요? 사실 지금의 `start`메서드는 *게임 시작*만 하는게 아니라 게임의 모든 과정을 총괄하는 역할이니까요!

2022-03-17 02:22 UTC, Hepheir commented on .gitattributes
> +*.java text eol=lf
불필요한 파일은 이후 커밋에서 제외시키도록 하겠습니다!

2022-03-17 02:23 UTC, Hepheir commented
@kth496 리뷰 감사합니다 :) 설명도 친절하게 적어주셔서 덕분에 쉽게 이해할 수 있었습니다.

남겨주신 코멘트를 바탕으로 코드를 더 개선해보겠습니다 :)

2022-03-17 02:36 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +    }
이 메소드명을 정하기위해서 저도 고민을 많이해보았습니다.

턴제 보드게임을 다루는 영문서에서 **플레이어가 두는 "수"** 를 **move**라고 표현하는 것을 보았고, 이 표현이 탁월하지는 않지만 저의 의도를 그나마 잘 표현할 수 있다고 생각했던 것 같습니다.

다른 메소드명 후보로는 `turn`이 라던가 `doPlayerAction`, `startTurn`, `doAction`, ... 등이 있었으나 아직도 "이거다!" 하는 명칭이 잘 떠오르지 않습니다... ㅠㅠ 선생님이 생각하시는 적절한 메서드 명에는 어떤게 있을까요... 저도 `move` 메소드의 새로운 이름으로 적절한 것을 계속 생각해보겠습니다!

2022-03-17 02:41 UTC, Hepheir commented on src/main/java/baseball/Game.java
> +    public void end();
앗.. 그렇군요!
생각해보면 반드시 오버라이드 해야하는 메소드의 접근제한자는 특수한 경우가 아닌이상 `public` 이어아야 할 테니깐요,,, 하나 배워갑니다! :)

2022-03-17 02:41 UTC, Hepheir commented on README.md
> +## 구현할 기능 목록 (과제)
칭찬 감사합니다 :)

2022-03-17 03:40 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        } while (app.promptStartNewGame());
선생님 말씀을 듣고보니 아래의 표현이 조금 더 일반적으로 기대대는 수준에 맞는 레벨이 되겠네요!

```suggestion
            app.start();
            app.end();
        } while (app.promptStartNewGame());
```

2022-03-17 03:43 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        } while (app.promptStartNewGame());
`start()` 메소드 속에서 호출되던 `end()`를 밖에서 실행하게 되었으니, 이에 맞게 `start()` 함수도 변경해야겠군요. 수정해보겠습니다 :)

2022-03-17 05:02 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        assert checkIndex(index);
아하! 그럼 `checkIndex()`의 사용은 지양하는대신 `IndexOutOfBoundException`으로 사용자에게 잘못된 사용에 대한 메시지를 던져주면 되겠군요! 그럼 사용자가 1~9 사이에서 숫자를 입력했는지를 검사하는 `checkValue()`에서는 또 다른 예외처리가 필요할 것 같은데, 어떤 Exception을 사용하는게 좋을까요,

[커밋 메시지 컨벤션](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#examples)처럼 다양한 예외 종류에 따라 사용하기 적절한 컨벤션이 정리된 문서가 혹시 있을까 찾아봐야겠군요... 갈길이 머네요 ㅠㅠ

2022-03-18 06:31 UTC, Hepheir commented
대규모... 수정이 있었습니다 선생님... 리뷰 부탁드립니다 :)

2022-03-18 06:33 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        } while (app.promptStartNewGame());
[80333fa](https://github.com/kth496/java-baseball-implement/pull/5/commits/80333fa1b5cc2c847e77f89e02cda6a351d3d766) 에서 `start()`를 `run()`으로 rename하고, 구조를 개편함으로서 해결했습니다.

2022-03-18 06:39 UTC, Hepheir commented on .gitattributes
> +*.java text eol=lf
[8e485c8](https://github.com/kth496/java-baseball-implement/pull/5/commits/8e485c8e65d132217b9a88b6fa1b1c0656ff0b74), [4bca0a5](https://github.com/kth496/java-baseball-implement/pull/5/commits/4bca0a54b3df50585340592e495e09741a019558),
[26cd2cf](https://github.com/kth496/java-baseball-implement/pull/5/commits/26cd2cf7bff56054652bebdb779756f3c818aa86) 에서 제외시켰습니다!

2022-03-18 06:42 UTC, Hepheir commented on src/main/java/baseball/Game.java
> +    public void end();
[f6d1161](https://github.com/kth496/java-baseball-implement/pull/5/commits/f6d11617a821dacc380761b350cf03b0aa97c95d)에서 생략가능한 접근제한자를 제거하였습니다 :)

2022-03-18 06:49 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        assert checkIndex(index);
`check...()`로 시작하는 메소드를 정의하여, 해당 메소드내에서 `IllegalArgumentException`를 발생시키는 방법으로 리펙터링하였습니다.


검증을 위한 메소드를 구현할때 아래와 같이 두 선택지가 있다면,

* 문제가 발견되었는지에 따라 boolean을 반환
* 발견된 문제에 적합한 예외/에러를 발생시킴

유지보수성에서는 후자가 더 유리할 것 같다는 생각이 들었습니다.

2022-03-18 06:50 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        System.out.println();
[ff4dfba](https://github.com/kth496/java-baseball-implement/pull/5/commits/ff4dfba3bf15ddf46a382b59e9cf3408143f2928)에서 별도의 클래스 `View`를 정의하여 개선하였습니다.

2022-03-18 06:53 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +    private void parseRawPlayerNumbers(String[] rawPlayerNumbers) throws IllegalArgumentException {
이름에서 느낄 수 있는 의도에 맞춰, 사용자가 반환값을 기대할 수 있는 메소드에 대하여 `ArrayList<Integer>` 혹은 `String`등을 반환하도록 하였습니다.

적용 예시: 
```java
private ArrayList<Integer> generateRandomNumbers() ...
```

```java
private static String buildStrikesAndBallsMessage(int strikes, int balls) ...
```

2022-03-18 06:56 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +    }
[6d0320d](https://github.com/kth496/java-baseball-implement/pull/5/commits/6d0320d914d45f01c60145b42b8b9ce27d795c2f)에서 메소드 명을 `onTurn()`으로 변경하였습니다!

2022-03-18 06:57 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +        System.out.println();
[ff4dfba](https://github.com/kth496/java-baseball-implement/pull/5/commits/ff4dfba3bf15ddf46a382b59e9cf3408143f2928)에서 `View` 클래스를 정의하고 하드코딩된 상수를 분리하였습니다.

2022-03-18 06:58 UTC, Hepheir commented on src/main/java/baseball/Application.java
> +    }
넵 참고하겠습니다 :)

2022-03-19 13:12 UTC, kth496 requested changes
피드백을 잘 반영해주셨네요 😃 리뷰를 남겼으니 한번 확인해보세요!

2022-03-19 13:12 UTC, kth496 commented on src/main/java/baseball/BaseballGame.java
> +    }
`isWin`메서드 이전에 strike의 갯수를 세어서 출력해주는 로직이 있는 상황입니다. 그렇다면 승리를 판단할때 또 다시 strike의 갯수를 세어줄 필요가 있을까요? 대규모 프로그램이라면 필요없는 연산으로 인해 성능이 저하될 요소가 될 수 있습니다.

2022-03-19 13:12 UTC, kth496 commented on src/main/java/baseball/BaseballGame.java
> +        ballsCnt -= countStrikes();
볼을 복잡하게 계산하지 않고 스트라이크의 갯수를 이용해서 깔끔하게 계산하신 부분 아주 좋습니다!

2022-03-19 13:12 UTC, kth496 commented on src/main/java/baseball/View.java
> +        String message = new String();
자바에서는 빈 문자열을 `""`으로 만듭니다. `new String()`은 좋은 방법이 아닙니다.

2022-03-19 13:12 UTC, kth496 commented on src/main/java/baseball/View.java
> +        }
seperator를 끼우는게 꼭 필요할까요? 사실 없어도 결과물을 만들수 있습니다!

2022-03-19 13:12 UTC, kth496 commented on src/main/java/baseball/Command.java
> +    }
`Enum`분리 아주 좋습니다! 상수의 업그레이드판이 바로 열거체이죠. 잘 사용하셨어요!

2022-03-23 07:25 UTC, closed without merging